# Generated by Django 5.2.8 on 2025-12-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='certification_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='medical_clearance',
            field=models.BooleanField(default=False, help_text='User confirmed they have no conflicting medical conditions'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='number_of_divers',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
